/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: heycronus (https://sketchfab.com/heycronus)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/retro-computer-pc-low-poly-3d-model-980ecb6ba9d748948b40a09bf7d855b4
Title: Retro Computer - PC Low Poly 3D Model
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

const RetroComputer = (props) => {
  const { nodes, materials } = useGLTF('/models/retro_computer.glb')
  const screenTexture = useTexture('/textures/screen.png')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.material_0}
        position={[0.063, 0, 0.438]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.material_0}
        position={[0.063, 0.375, 0.438]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.material_0}
        position={[0.063, 0.5, 0.438]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.material_0}
        position={[0.063, 0.563, 0.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.material_0}
        position={[0.063, 1.5, 0.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.material_0}
        position={[0.063, 1.313, 0.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.material_0}
        position={[-1.031, 1.313, 0.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.material_0}
        position={[-0.094, 1.313, 0.313]}
      >
        {/* <meshMatcapMaterial map={screenTexture} /> */}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.material_0}
        position={[-0.094, 1.313, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.material_0}
        position={[-0.094, 1.188, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.material_0}
        position={[0.188, 0, -0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials.material_0}
        position={[-0.75, 0, -0.625]}
      />
    </group>
  )
}

useGLTF.preload('/models/retro_computer.glb')

export default RetroComputer
