// // /*
// // Auto-generated by: https://github.com/pmndrs/gltfjsx
// // Author: hyti131 (https://sketchfab.com/hyti131)
// // License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// // Source: https://sketchfab.com/3d-models/watering-pot-8a7627327df5436d9f39b6d470d491db
// // Title: Watering Pot
// // */

import { useGLTF } from '@react-three/drei'
import { useEffect, useRef } from 'react'
import { forwardRef } from 'react'

const VoxelWateringPot = forwardRef((props, groupRef) => {
  const { nodes, materials } = useGLTF('/models/voxel_watering_pot.glb')

  const potRef = useRef()

  useEffect(() => {
    if (nodes.Object_2?.geometry) {
      nodes.Object_2.geometry.center() // Thay đổi tâm tâm bounding box về [0,0,0]
    }
  }, [nodes])

  // oxyz của group và pot
  // useEffect(() => {
  //   if (potRef.current) {
  //     const axes = new AxesHelper(2) // độ dài của trục
  //     potRef.current.add(axes) // gắn axes vào object
  //   }
  //   if (groupRef.current) {
  //     const axes = new AxesHelper(2)
  //     groupRef.current.add(axes)
  //   }
  // }, [])

  return (
    <group ref={groupRef} {...props}>
      <mesh
        ref={potRef}
        geometry={nodes.Object_2.geometry}
        material={materials.palette}
        rotation={[1.74, 2.44, 1.38]} //vị trí của pot trong hệ trục của pot
      />
    </group>
  )
})

useGLTF.preload('/models/voxel_watering_pot.glb')
export default VoxelWateringPot
