/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ini_andri (https://sketchfab.com/ini_andri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mug-6b2bdac758694312b2ca44acac21c6a9
Title: mug
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'

const VoxelMug = (props) => {
  const { nodes, materials } = useGLTF('/models/voxel_mug.glb')
  const targetRef = useRef()
  //   useGSAP(() => {
  //     gsap.to(targetRef.current.position, {
  //       y: targetRef.current.position.y + 0.5,
  //       duration: 1.5,
  //       repeat: -1,
  //       yoyo: true,
  //     })
  //   })
  return (
    <Float floatIntensity={1} rotationIntensity={0.5} floatingRange={[0.1, 0.5]}>
      <group {...props} dispose={null} ref={targetRef}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.VoxMaterial_96}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.VoxMaterial_112}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.VoxMaterial_114}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.VoxMaterial_115}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.VoxMaterial_130}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.VoxMaterial_132}
            />
          </group>
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('/models/voxel_mug.glb')
export default VoxelMug
