/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Business boy (https://sketchfab.com/Baboyo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/001-bulbasaur-0034cede682942c5880f8d6effbbeac2
Title: 001 - Bulbasaur
*/

import { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const VoxelBulbasaur = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/models/voxel_bulbasaur.glb')
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Matrix_bulbasaur_material_0.geometry}
        material={materials.bulbasaur_material}
        position={[-10.895, 5.564, -21.562]}
        rotation={[0, 0, -0.037]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Matrix_1_bulbasaur_material_0.geometry}
        material={materials.bulbasaur_material}
        position={[-2.216, 3.168, -14.558]}
        rotation={[0, 0, -0.191]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Matrix_2_bulbasaur_material_0.geometry}
        material={materials.bulbasaur_material}
        position={[-10.565, 0.064, -20.368]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Matrix_3_bulbasaur_material_0.geometry}
        material={materials.bulbasaur_material}
        position={[-9.545, 0.064, -8.644]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Matrix_4_bulbasaur_material_0.geometry}
        material={materials.bulbasaur_material}
        position={[3.179, 0.063, -5.34]}
        rotation={[0, 0.149, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Matrix_5_bulbasaur_material_0.geometry}
        material={materials.bulbasaur_material}
        position={[4.534, 0.063, -24.368]}
        rotation={[0, -0.149, 0]}
      />
    </group>
  )
})

useGLTF.preload('/models/voxel_bulbasaur.glb')
export default VoxelBulbasaur
