/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Johnny Boi (https://sketchfab.com/johnnyboi404)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-flowers-98e89b7cca9440eca527a1186e585f7f
Title: Voxel Flowers
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const VoxelFlowers = (props) => {
  const { nodes, materials } = useGLTF('/models/voxel_flowers.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.palette}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.062}
      />
    </group>
  )
}

useGLTF.preload('/models/voxel_flowers.glb')

export default VoxelFlowers
