/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: cmzw (https://sketchfab.com/cmzw)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-world-9fbc3f1c776f4282ab55f7f14811fe79
Title: Voxel World
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const VoxelWorld = (props) => {
  const { nodes, materials } = useGLTF('/models/voxel_world.glb')
  const groupRef = useRef()

  // Xoay mô hình mỗi frame quanh trục Y
  useFrame((state, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.y += delta * 0.08 //  radian/giây
    }
  })
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Clouds}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/voxel_world.glb')
export default VoxelWorld
