/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ZentoZekto (https://sketchfab.com/ZentoZekto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-robot-0a719b7c4ef44a70a37e0563d9db8bdc
Title: Voxel Robot
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'
import { useState } from 'react'

const VoxelRobot = (props) => {
  const { nodes, materials } = useGLTF('/models/voxel_robot.glb')
  //   const cubeRef = useRef()
  //   const [hovered, setHovered] = useState(false)

  //   useGSAP(() => {
  //     gsap
  //       .timeline({
  //         repeat: -1,
  //         repeatDelay: 0.5,
  //       })
  //       .to(cubeRef.current.rotation, {
  //         y: hovered ? '+=2' : `+=${Math.PI * 2}`,
  //         x: hovered ? '+=2' : `-=${Math.PI * 2}`,
  //         duration: 2.5,
  //         stagger: {
  //           each: 0.15,
  //         },
  //       })
  //   })
  return (
    <Float floatIntensity={2}>
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            //ref={cubeRef}
            castShadow
            receiveShadow
            geometry={nodes.Object_2.geometry}
            material={materials.palette}
            position={[-3.5, -4.5, 0]}
            //onPointerEnter={() => setHovered(true)}
          />
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('/models/voxel_robot.glb')
export default VoxelRobot
