/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SpaceMonkeyBoi (https://sketchfab.com/SpaceMonkeyBoi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monarch-butterfly-ba56ad0f0b0e45ecbf65eb9547c73237
Title: Monarch Butterfly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const VoxelButterfly = (props) => {
  const { nodes, materials } = useGLTF('/models/voxel_butterfly.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.6, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.material_0}
          position={[0, -1.5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.material_0}
          position={[0, -1.5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.material_0}
          position={[0, -1.5, 0]}
        />
      </group>
      <group position={[0, 1.6, 0]} rotation={[-0.635, 0, 0]}>
        <group rotation={[0, -Math.PI / 4, 0]}>
          <group position={[0.063, -0.063, 0.094]} rotation={[0, -0.384, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_35.geometry}
              material={materials.material_0}
              position={[-0.063, -1.438, -0.094]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_32.geometry}
            material={materials.material_0}
            position={[0, -1.5, 0]}
          />
        </group>
        <group rotation={[0, Math.PI / 4, 0]}>
          <group position={[-0.063, -0.063, 0.094]} rotation={[0, 0.384, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_41.geometry}
              material={materials.material_0}
              position={[0.063, -1.438, -0.094]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_38.geometry}
            material={materials.material_0}
            position={[0, -1.5, 0]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.material_0}
          position={[0, -1.5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.material_0}
          position={[0, -1.5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.material_0}
          rotation={[-0.131, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.material_0}
          rotation={[-0.131, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.material_0}
          rotation={[-0.131, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.material_0}
          rotation={[-0.131, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials.material_0}
          rotation={[-0.131, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials.material_0}
          rotation={[-0.131, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/voxel_butterfly.glb')
export default VoxelButterfly
