/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pistachiopony (https://sketchfab.com/pistachiopony)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pluto-e32b1077fe334372b8a5f07c203a67df
Title: Pluto
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const VoxelPluto = (props) => {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/models/voxel_pluto.glb')
  useFrame((state, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.y += delta * 0.5 // tốc độ quay
    }
  })
  return (
    // <Float floatIntensity={1}>
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['model-material'].geometry}
            material={materials['model-material']}
            position={[0, 15, 0]}
          />
        </group>
      </group>
    </group>
    // </Float>
  )
}

useGLTF.preload('/models/voxel_pluto.glb')

export default VoxelPluto
