/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gundy (https://sketchfab.com/RomualdDubois)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bee-bzzz-80f9b49d2ad94c76bc8b02b6eb11e8cc
Title: Bee Bzzz 🐝
*/

import { useEffect, forwardRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const VoxelBee = forwardRef(({ hasBeeFlown, ...props }, ref) => {
  const { nodes, materials, animations } = useGLTF('/models/voxel_bee.glb')
  const { actions } = useAnimations(animations, ref)
  useEffect(() => {
    // Chạy tất cả animation
    if (actions && hasBeeFlown) {
      Object.values(actions).forEach((action) => {
        action.reset().fadeIn(0.5).play()
      })
    }
  }, [actions, hasBeeFlown])
  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_4" position={[0, 0.016, 0]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.palette}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Bee_3" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/models/voxel_bee.glb')
export default VoxelBee
