/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const VoxelReactLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/voxel_react_logo.glb')
  return (
    <Float floatIntensity={1}>
      <group scale={0.3} {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.geometry_0.geometry}
          material={nodes.geometry_0.material}
        >
          <meshStandardMaterial color="#61DAFB" />
        </mesh>
      </group>
    </Float>
  )
}

useGLTF.preload('/models/voxel_react_logo.glb')
export default VoxelReactLogo
